### ISSUE TITLE
Update test scripts and CI after nerdctl v2.0 released

### ISSUE THREAD

**Issue by naoki9911** [rootless-containers/bypass4netns#62]
https://github.com/containerd/nerdctl/pull/2906

In nerdctl v2, `labels` not passed through the OCI runtime since nerdctl v2.0, with an exception for `nerdctl/bypass4netns`.
We should migrate to `--annotation` (`--annotation nerdctl/bypass4netns`).

**Comment by AkihiroSuda** [comment]
- https://github.com/rootless-containers/bypass4netns/pull/64
