### ISSUE TITLE
how to apply to rootless dockerd?

### ISSUE THREAD

**Issue by thetredev** [rootless-containers/bypass4netns#85]
Hi,

I have followed the steps to run `dockerd` rootless (https://docs.docker.com/engine/security/rootless) and it works great with `slirp4netns`. But it's slow... because of that I wanted to change the net/port driver (https://docs.docker.com/engine/security/rootless/#networking-errors). So I went ahead and cloned this repo, checked out tag `0.4.1` and ran `make` + `sudo make install`.

When I run `bypass4netns` by itself, I get the following output:
```
$ bypass4netns
INFO[0000] SocketPath: /run/user/1000/bypass4netns.sock 
INFO[0000] 127.0.0.0/8 is added to ignore               
INFO[0000] Waiting for seccomp file descriptors
```
Not sure if this is expected or not, though.

To use `bypass4netns` for rootless `dockerd`, I tried the following `docker.service` override:
```
$ cat ~/.config/systemd/user/docker.service.d/override.conf
[Service]
Environment="DOCKERD_ROOTLESS_ROOTLESSKIT_NET=bypass4netns"
Environment="DOCKERD_ROOTLESS_ROOTLESSKIT_PORT_DRIVER=bypass4netns"
```

Sadly, this way `dockerd` won't start and I can't get any logs:
```
$ systemctl --user --no-pager status docker
× docker.service - Docker Application Container Engine (Rootless)
     Loaded: loaded (/home/kube/.config/systemd/user/docker.service; enabled; preset: enabled)
    Drop-In: /home/kube/.config/systemd/user/docker.service.d
             └─override.conf
     Active: failed (Result: exit-code) since Thu 2024-06-13 21:31:38 CEST; 1min 32s ago
   Duration: 13min 57.454s
       Docs: https://docs.docker.com/go/rootless/
    Process: 8655 ExecStart=/usr/bin/dockerd-rootless.sh (code=exited, status=1/FAILURE)
   Main PID: 8655 (code=exited, status=1/FAILURE)
        CPU: 4ms
```
```
$ journalctl --user --no-pager -xeu docker.service
No journal files were found.
-- No entries --
```

I'm lost. I *believe* this has something to do with the `seccomp` profile from `test/seccomp.json.sh` missing from the system. But I have not found any guide on how to install this profile system-wide and make `dockerd` use it for all containers. Does anyone know how to do this?

**Comment by AkihiroSuda** [comment]
See https://github.com/rootless-containers/bypass4netns/tree/v0.4.1?tab=readme-ov-file#hard-way-dockerpodmannerdctl

**Comment by thetredev** [comment]
@AkihiroSuda ahhhhhhh I was blind lol I missed the `--security-opt` option. Thank you! Closing.
